language: node_js
node_js:
    - '10'
cache:
    yarn: true
    directories:
        - node_modules
before_install:
    - npm install -g yarn firebase-tools
install:
    - yarn
script:
    - yarn build

after_success:
    - firebase use default --token $FIREBASE_TOKEN
    - travis_wait firebase deploy -m "Travis auto-deploy PR ${TRAVIS_PULL_REQUEST}" --non-interactive --token $FIREBASE_TOKEN

branches:
    only:
        - master
